"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CodeRequest(_message.Message):
    """/////////////////////////////////////////////////////// 请求消息"""

    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    auth: _builtins.str
    """需要鉴权"""
    def __init__(
        self,
        *,
        auth: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CodeRequest: _TypeAlias = CodeRequest  # noqa: Y015

@_typing.final
class CodeStatusUpdateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTH_FIELD_NUMBER: _builtins.int
    INDICES_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    auth: _builtins.str
    indices: _builtins.int
    """代码编号"""
    id: _builtins.str
    """学号"""
    status: _builtins.int
    """当前代码的处理状态(比如编译成功、编译失败、运行成功....)"""
    data: _builtins.str
    """返回的数据"""
    def __init__(
        self,
        *,
        auth: _builtins.str = ...,
        indices: _builtins.int = ...,
        id: _builtins.str = ...,
        status: _builtins.int = ...,
        data: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth", b"auth", "data", b"data", "id", b"id", "indices", b"indices", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CodeStatusUpdateRequest: _TypeAlias = CodeStatusUpdateRequest  # noqa: Y015

@_typing.final
class Empty(_message.Message):
    """//////////////////////////////////////////////////////// 响应消息"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Empty: _TypeAlias = Empty  # noqa: Y015

@_typing.final
class CodeReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADERURL_FIELD_NUMBER: _builtins.int
    SOURCEURL_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    INDICES_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    MSG_FIELD_NUMBER: _builtins.int
    headerUrl: _builtins.str
    """头文件下载路径"""
    sourceUrl: _builtins.str
    """源文件下载路径"""
    id: _builtins.str
    """学生id"""
    indices: _builtins.int
    """代码编号"""
    ok: _builtins.bool
    """是否成功获取到源码"""
    msg: _builtins.str
    """消息"""
    def __init__(
        self,
        *,
        headerUrl: _builtins.str = ...,
        sourceUrl: _builtins.str = ...,
        id: _builtins.str = ...,
        indices: _builtins.int = ...,
        ok: _builtins.bool = ...,
        msg: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["headerUrl", b"headerUrl", "id", b"id", "indices", b"indices", "msg", b"msg", "ok", b"ok", "sourceUrl", b"sourceUrl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CodeReply: _TypeAlias = CodeReply  # noqa: Y015
