# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protoc_pb2 as protoc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protoc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodeStub(object):
    """////////////////////////////////////////////////////// 定义服务
    ///Judge通信
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCode = channel.unary_unary(
                '/Code/GetCode',
                request_serializer=protoc__pb2.CodeRequest.SerializeToString,
                response_deserializer=protoc__pb2.CodeReply.FromString,
                _registered_method=True)
        self.CodeStatusUpdate = channel.unary_unary(
                '/Code/CodeStatusUpdate',
                request_serializer=protoc__pb2.CodeStatusUpdateRequest.SerializeToString,
                response_deserializer=protoc__pb2.Empty.FromString,
                _registered_method=True)


class CodeServicer(object):
    """////////////////////////////////////////////////////// 定义服务
    ///Judge通信
    """

    def GetCode(self, request, context):
        """获取一份待批改的代码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CodeStatusUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCode,
                    request_deserializer=protoc__pb2.CodeRequest.FromString,
                    response_serializer=protoc__pb2.CodeReply.SerializeToString,
            ),
            'CodeStatusUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.CodeStatusUpdate,
                    request_deserializer=protoc__pb2.CodeStatusUpdateRequest.FromString,
                    response_serializer=protoc__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Code', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Code', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Code(object):
    """////////////////////////////////////////////////////// 定义服务
    ///Judge通信
    """

    @staticmethod
    def GetCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Code/GetCode',
            protoc__pb2.CodeRequest.SerializeToString,
            protoc__pb2.CodeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CodeStatusUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Code/CodeStatusUpdate',
            protoc__pb2.CodeStatusUpdateRequest.SerializeToString,
            protoc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
