# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protoc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protoc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cprotoc.proto\"\x1b\n\x0b\x43odeRequest\x12\x0c\n\x04\x61uth\x18\x01 \x01(\t\"b\n\x17\x43odeStatusUpdateRequest\x12\x0c\n\x04\x61uth\x18\x01 \x01(\t\x12\x0f\n\x07indices\x18\x02 \x01(\x03\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\"\x07\n\x05\x45mpty\"g\n\tCodeReply\x12\x11\n\theaderUrl\x18\x01 \x01(\t\x12\x11\n\tsourceUrl\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0f\n\x07indices\x18\x04 \x01(\x03\x12\n\n\x02ok\x18\x05 \x01(\x08\x12\x0b\n\x03msg\x18\x06 \x01(\t2a\n\x04\x43ode\x12#\n\x07GetCode\x12\x0c.CodeRequest\x1a\n.CodeReply\x12\x34\n\x10\x43odeStatusUpdate\x12\x18.CodeStatusUpdateRequest\x1a\x06.EmptyB\x0cZ\n./grpc_apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./grpc_api'
  _globals['_CODEREQUEST']._serialized_start=16
  _globals['_CODEREQUEST']._serialized_end=43
  _globals['_CODESTATUSUPDATEREQUEST']._serialized_start=45
  _globals['_CODESTATUSUPDATEREQUEST']._serialized_end=143
  _globals['_EMPTY']._serialized_start=145
  _globals['_EMPTY']._serialized_end=152
  _globals['_CODEREPLY']._serialized_start=154
  _globals['_CODEREPLY']._serialized_end=257
  _globals['_CODE']._serialized_start=259
  _globals['_CODE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
