// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: protoc.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Code_GetCode_FullMethodName          = "/Code/GetCode"
	Code_CodeStatusUpdate_FullMethodName = "/Code/CodeStatusUpdate"
)

// CodeClient is the client API for Code service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ////////////////////////////////////////////////////// 定义服务
// ///Judge通信
type CodeClient interface {
	//获取一份待批改的代码
	GetCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeReply, error)
	CodeStatusUpdate(ctx context.Context, in *CodeStatusUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
}

type codeClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeClient(cc grpc.ClientConnInterface) CodeClient {
	return &codeClient{cc}
}

func (c *codeClient) GetCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeReply)
	err := c.cc.Invoke(ctx, Code_GetCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeClient) CodeStatusUpdate(ctx context.Context, in *CodeStatusUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Code_CodeStatusUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeServer is the server API for Code service.
// All implementations must embed UnimplementedCodeServer
// for forward compatibility.
//
// ////////////////////////////////////////////////////// 定义服务
// ///Judge通信
type CodeServer interface {
	//获取一份待批改的代码
	GetCode(context.Context, *CodeRequest) (*CodeReply, error)
	CodeStatusUpdate(context.Context, *CodeStatusUpdateRequest) (*Empty, error)
	mustEmbedUnimplementedCodeServer()
}

// UnimplementedCodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeServer struct{}

func (UnimplementedCodeServer) GetCode(context.Context, *CodeRequest) (*CodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCode not implemented")
}
func (UnimplementedCodeServer) CodeStatusUpdate(context.Context, *CodeStatusUpdateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CodeStatusUpdate not implemented")
}
func (UnimplementedCodeServer) mustEmbedUnimplementedCodeServer() {}
func (UnimplementedCodeServer) testEmbeddedByValue()              {}

// UnsafeCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeServer will
// result in compilation errors.
type UnsafeCodeServer interface {
	mustEmbedUnimplementedCodeServer()
}

func RegisterCodeServer(s grpc.ServiceRegistrar, srv CodeServer) {
	// If the following call panics, it indicates UnimplementedCodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Code_ServiceDesc, srv)
}

func _Code_GetCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeServer).GetCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Code_GetCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeServer).GetCode(ctx, req.(*CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Code_CodeStatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeStatusUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeServer).CodeStatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Code_CodeStatusUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeServer).CodeStatusUpdate(ctx, req.(*CodeStatusUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Code_ServiceDesc is the grpc.ServiceDesc for Code service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Code_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Code",
	HandlerType: (*CodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCode",
			Handler:    _Code_GetCode_Handler,
		},
		{
			MethodName: "CodeStatusUpdate",
			Handler:    _Code_CodeStatusUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc.proto",
}
