// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: protoc.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

///////////////////////////////////////////////////////// 请求消息
type CodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"` //需要鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeRequest) Reset() {
	*x = CodeRequest{}
	mi := &file_protoc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeRequest) ProtoMessage() {}

func (x *CodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeRequest.ProtoReflect.Descriptor instead.
func (*CodeRequest) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{0}
}

func (x *CodeRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type CodeStatusUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Indices       int64                  `protobuf:"varint,2,opt,name=indices,proto3" json:"indices,omitempty"` //代码编号
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`            //学号
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`   //当前代码的处理状态(比如编译成功、编译失败、运行成功....)
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`        //返回的数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeStatusUpdateRequest) Reset() {
	*x = CodeStatusUpdateRequest{}
	mi := &file_protoc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeStatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeStatusUpdateRequest) ProtoMessage() {}

func (x *CodeStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeStatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*CodeStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{1}
}

func (x *CodeStatusUpdateRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *CodeStatusUpdateRequest) GetIndices() int64 {
	if x != nil {
		return x.Indices
	}
	return 0
}

func (x *CodeStatusUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodeStatusUpdateRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CodeStatusUpdateRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

////////////////////////////////////////////////////////// 响应消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protoc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{2}
}

type CodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeaderUrl     string                 `protobuf:"bytes,1,opt,name=headerUrl,proto3" json:"headerUrl,omitempty"` //头文件下载路径
	SourceUrl     string                 `protobuf:"bytes,2,opt,name=sourceUrl,proto3" json:"sourceUrl,omitempty"` //源文件下载路径
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`               //学生id
	Indices       int64                  `protobuf:"varint,4,opt,name=indices,proto3" json:"indices,omitempty"`    //代码编号
	Ok            bool                   `protobuf:"varint,5,opt,name=ok,proto3" json:"ok,omitempty"`              //是否成功获取到源码
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`             //消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeReply) Reset() {
	*x = CodeReply{}
	mi := &file_protoc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeReply) ProtoMessage() {}

func (x *CodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeReply.ProtoReflect.Descriptor instead.
func (*CodeReply) Descriptor() ([]byte, []int) {
	return file_protoc_proto_rawDescGZIP(), []int{3}
}

func (x *CodeReply) GetHeaderUrl() string {
	if x != nil {
		return x.HeaderUrl
	}
	return ""
}

func (x *CodeReply) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *CodeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodeReply) GetIndices() int64 {
	if x != nil {
		return x.Indices
	}
	return 0
}

func (x *CodeReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CodeReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protoc_proto protoreflect.FileDescriptor

const file_protoc_proto_rawDesc = "" +
	"\n" +
	"\fprotoc.proto\"!\n" +
	"\vCodeRequest\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\"\x83\x01\n" +
	"\x17CodeStatusUpdateRequest\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\x12\x18\n" +
	"\aindices\x18\x02 \x01(\x03R\aindices\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"\a\n" +
	"\x05Empty\"\x93\x01\n" +
	"\tCodeReply\x12\x1c\n" +
	"\theaderUrl\x18\x01 \x01(\tR\theaderUrl\x12\x1c\n" +
	"\tsourceUrl\x18\x02 \x01(\tR\tsourceUrl\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x18\n" +
	"\aindices\x18\x04 \x01(\x03R\aindices\x12\x0e\n" +
	"\x02ok\x18\x05 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg2a\n" +
	"\x04Code\x12#\n" +
	"\aGetCode\x12\f.CodeRequest\x1a\n" +
	".CodeReply\x124\n" +
	"\x10CodeStatusUpdate\x12\x18.CodeStatusUpdateRequest\x1a\x06.EmptyB\fZ\n" +
	"./grpc_apib\x06proto3"

var (
	file_protoc_proto_rawDescOnce sync.Once
	file_protoc_proto_rawDescData []byte
)

func file_protoc_proto_rawDescGZIP() []byte {
	file_protoc_proto_rawDescOnce.Do(func() {
		file_protoc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_proto_rawDesc), len(file_protoc_proto_rawDesc)))
	})
	return file_protoc_proto_rawDescData
}

var file_protoc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protoc_proto_goTypes = []any{
	(*CodeRequest)(nil),             // 0: CodeRequest
	(*CodeStatusUpdateRequest)(nil), // 1: CodeStatusUpdateRequest
	(*Empty)(nil),                   // 2: Empty
	(*CodeReply)(nil),               // 3: CodeReply
}
var file_protoc_proto_depIdxs = []int32{
	0, // 0: Code.GetCode:input_type -> CodeRequest
	1, // 1: Code.CodeStatusUpdate:input_type -> CodeStatusUpdateRequest
	3, // 2: Code.GetCode:output_type -> CodeReply
	2, // 3: Code.CodeStatusUpdate:output_type -> Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_proto_init() }
func file_protoc_proto_init() {
	if File_protoc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_proto_rawDesc), len(file_protoc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_proto_goTypes,
		DependencyIndexes: file_protoc_proto_depIdxs,
		MessageInfos:      file_protoc_proto_msgTypes,
	}.Build()
	File_protoc_proto = out.File
	file_protoc_proto_goTypes = nil
	file_protoc_proto_depIdxs = nil
}
