- name: Sync to Gitee
  run: |
    git remote add gitee https://crackermmzz:${{ secrets.GITEE_TOKEN }}@gitee.com/crackermmzz/newaoe-frontend-backend.git
    git push gitee --all
    git push gitee --tags