name: Sync to Gitee

on:
  push:
    branches:
      - "**"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync current branch to Gitee
        run: |
          git remote add gitee https://crackermmzz:${{ secrets.GITEE_TOKEN }}@gitee.com/crackermmzz/newaoe-frontend-backend.git

          # 同步当前触发的分支
          git push gitee HEAD:${{ github.ref_name }}

          # 同步 tag（可选）
          git push gitee --tags