name: Sync to Gitee

on:
  push:
    branches:
      - "judge"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync judge branch to Gitee
        run: |
          git remote add gitee https://crackermmzz:${{ secrets.GITEE_TOKEN }}@gitee.com/crackermmzz/newaoe-frontend-backend.git

          # 只同步 judge 分支
          git push gitee judge

          # 同步 tag（如果需要）
          git push gitee --tags